import { localized as l, type WikiCategory } from './model.js';
export const wikiCategories: readonly WikiCategory[] = [
  { id: 'basics', icon: 'guide', title: l('Getting started', 'Başlangıç'), description: l('Learn your first actions, the core game loop and the controls that help you make your next decision.', 'İlk adımlarını, oyun döngüsünü ve bir sonraki kararını vermeni kolaylaştıran kontrolleri öğren.') },
  { id: 'worlds', icon: 'planet', title: l('Worlds & colonies', 'Gezegenler ve koloniler'), description: l('Understand capitals, neutral worlds, settlement, occupation, loyalty and the ways colonies can change hands.', "Ana gezegenleri, tarafsız gezegenleri, yerleşimi, işgali, sadakati ve kolonilerin nasıl el değiştirdiğini öğren.") },
  { id: 'economy', icon: 'alloy', title: l('Economy & production', 'Ekonomi ve üretim'), description: l('Follow resources from the Works into the Store, plan your queues and protect the stock that pays for your fleet.', "Kaynakların üretimden depoya yolculuğunu izle, sıralarını planla ve filonu finanse eden stoğu koru.") },
  { id: 'buildings', icon: 'core', title: l('Buildings', 'Binalar'), description: l('Compare every planetary building, its upgrade costs, capacities and the decisions each new level opens.', 'Her gezegen binasını, yükseltme bedellerini, kapasitelerini ve yeni seviyelerin etkilerini karşılaştır.') },
  { id: 'hardware', icon: 'telescope', title: l('Instruments & orbit', "Gezegen cihazları ve yörünge"), description: l('Choose between seeing, shielding, concealment and orbital bonuses; check the current level and price tables.', 'Görüş, kalkan, gizlenme ve yörünge bonusları arasında seçim yap; güncel seviye ve bedel tablolarını incele.') },
  { id: 'research', icon: 'research', title: l('Research', 'Araştırmalar'), description: l('Explore every commander-wide research project, its prerequisites, level costs and effect on your empire.', "Tüm gezegenlerinde geçerli araştırmaları, önkoşullarını, seviye bedellerini ve gezegenlerine etkilerini keşfet.") },
  { id: 'fleet', icon: 'fleet', title: l('Fleet & flights', 'Filo ve uçuşlar'), description: l('Compare all ships and ground guns; learn hangar room, fuel, flight bays, damage and returning safely.', 'Tüm gemileri ve yer savunmalarını karşılaştır; Hangar alanını, yakıtı, uçuş rampalarını, hasarı ve dönüşü öğren.') },
  { id: 'combat', icon: 'attack', title: l('Combat & strategy', 'Savaş ve strateji'), description: l('Read the counter cycle, victory grades, raid limits, loot, tactical retreat and strategic weapon rules.', "Sınıf döngüsünü, zafer derecelerini, akın sınırlarını, yağmayı, taktik çekilmeyi ve stratejik silahları öğren.") },
  { id: 'intel', icon: 'telescope', title: l('Intelligence', 'İstihbarat'), description: l('Separate what is public from what you must measure: telescope watches, radar warnings, probes and dated reports.', 'Herkese açık bilgiyi ölçmen gereken bilgiden ayır: teleskop gözlemleri, radar uyarıları, sondalar ve tarihli raporlar.') },
  { id: 'galaxy', icon: 'galaxy', title: l('Galaxy & events', 'Galaksi ve etkinlikler'), description: l('Learn mining, pirates, merchants, convoys, radiation and the contested monuments that reward holding a position.', 'Madenciliği, korsanları, tüccarları, konvoyları, radyasyonu ve filo bulundurarak döteryum kazanılan anıtları öğren.') },
  { id: 'clan', icon: 'clan', title: l('Clans', 'Klanlar'), description: l('Coordinate membership, gifts, defensive support and shared attacks without confusing their different fleet rules.', 'Üyeliği, yardımları, savunma desteğini ve ortak saldırıları, farklı filo kurallarını anlayarak koordine et.') },
  { id: 'season', icon: 'leaderboard', title: l('Season & commander', 'Sezon ve komutan'), description: l('Understand Dominion, season endings, rewards, cosmetic identity and playing after a move to Silent Space.', "Hâkimiyet puanını, sezon sonunu, ödülleri, gezegen görünümlerini ve Sessiz Uzay’a geçişten sonra oynamayı öğren.") },
];
