import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Generate from the production game block, so CSP, SSE and asset behavior stay
// in one place. Printing a candidate does not install or reload any vhost.
const source = readFileSync(resolve(import.meta.dirname, '../deploy/nginx/astera.conf'), 'utf8');
const upstream = /^upstream astera_api \{[\s\S]*?^\}/m.exec(source)?.[0];
const gameStart = source.indexOf('# ── the game');
if (!upstream || gameStart === -1) {
  throw new Error('Production nginx template no longer has the expected upstream/game blocks');
}

function stage(text) {
  return text
    .replaceAll('astera_api', 'astera_stage_api')
    .replaceAll('asteraonline.space', 'stage.asteraonline.space')
    .replaceAll('/var/www/astera;', '/var/www/astera-stage;')
    .replaceAll('127.0.0.1:3200', '127.0.0.1:3300')
    .replaceAll('127.0.0.1:3201', '127.0.0.1:3301')
    .replaceAll('127.0.0.1:3202', '127.0.0.1:3302');
}

process.stdout.write(`# Generated by tools/stage-nginx.mjs from the production vhost.
${stage(upstream)}

server {
    listen 80;
    listen [::]:80;
    server_name stage.asteraonline.space;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://stage.asteraonline.space$request_uri; }
}

${stage(source.slice(gameStart))}`);
